### ISSUE TITLE
[Database] Slave pulling

### ISSUE THREAD

**Issue by JeyM1** [Pathfinder-Systems/pathfinder-core#16]
### Problem:
While setting up job for render, we need some mechanism to pull (group) some slaves and give the job only to them, keeping other slaves free (NOT RACISM!).

**Comment by JeyM1** [comment]
![pathfinder_core_slave](https://user-images.githubusercontent.com/46285162/95027267-e5ce4780-069f-11eb-9ae3-fb6fffd41e6e.png)

**Comment by DanilAndreev** [comment]
Added slave pools mechsnism. We can create pools inside each organiztion and add slaves to pools.
![image](https://user-images.githubusercontent.com/33941552/95199779-0b656900-07e6-11eb-915b-48f793f74499.png)
